pipeline {
  agent any
  environment {
    REPO_URL = "https://github.com/bjjd18021994/helm-charts.git"
    GITHUB_CREDENTIALS = credentials('github-credentials-id')
    CHART_DIR = "helm/project-service"
    BRANCH = "gh-pages"
  }
  tools {
    maven 'M3'
  }
  stages {
    stage('Checkout from Git Repository') {
      steps {
        git url: 'https://github.com/bjjd18021994/bjjd-services.git', branch: 'master'
      }
    }
    stage('Build Project') {
      steps {
        dir('project-service') {
            sh "mvn clean install -DskipTests -Pkubernetes"
            script {
              def version = sh script: 'mvn help:evaluate -Dexpression=project.version -q -DforceStdout', returnStdout: true
              print version
              env.version = version
            }
          }
      }
    }
}