pipeline {
  agent any
  environment {
    REPO_URL = "https://github.com/bjjd18021994/helm-charts.git"
    GITHUB_CREDENTIALS = credentials('github-credentials-id')
    BRANCH = "gh-pages"
  }
  tools {
    maven 'M3'
  }
  stages {
    stage('Checkout from Git Repository') {
      steps {
        git url: 'https://github.com/bjjd18021994/bjjd-services.git', branch: 'master'
      }
    }
    stage('Build Project') {
      steps {
            withCredentials([usernamePassword(
              credentialsId: 'dockerhub-creds',
              usernameVariable: 'DOCKER_USERNAME',
              passwordVariable: 'DOCKER_PASSWORD'
            )]) {
                echo "Building the project and push the Docker image for Project Service..."
                sh "mvn clean install -pl project-service -am -DskipTests -Pkubernetes"
            }
      }
    }
  }
}