<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
   
    <parent>
		<groupId>com.jmk</groupId>
		<artifactId>bjjd-services</artifactId>
		<version>0.0.1.RELEASE</version>
	</parent>
	
    <artifactId>account-service</artifactId>
    <packaging>jar</packaging>
    <name>account-service</name>
  <dependencies>
		<dependency>
			<groupId>com.github.joschi.jackson</groupId>
			<artifactId>jackson-datatype-threetenbp</artifactId>
			<version>2.6.4</version>
		</dependency>
		<!-- Bean Validation API support -->
		<dependency>
			<groupId>javax.validation</groupId>
			<artifactId>validation-api</artifactId>
		</dependency>
		<dependency>
			<groupId>com.jmk</groupId>
			<artifactId>common-service</artifactId>
            <version>${project.version}</version>
		</dependency>
		<!-- Starter for using Spring Data JPA with Hibernate to store and retrieve 
			data in a relational database. -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<!--MySQL provides connectivity -->
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>8.0.25</version><!--$NO-MVN-MAN-VER$ -->
		</dependency>
		
	</dependencies>
    <profiles>
        <profile>
            <id>kubernetes</id>
            <properties>
                <spring.profiles.active>kubernetes</spring.profiles.active>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.google.cloud.tools</groupId>
                        <artifactId>jib-maven-plugin</artifactId>
                        <version>${jib-maven-plugin.version}</version>
                        <configuration>
                            <from>
                                <image>eclipse-temurin:17-jre-jammy</image>
                            </from>
                            <to>
                                <image>registry.hub.docker.com/bjjd18021994/account-service:${project.version}</image>
                                <auth>
                                    <username>${env.DOCKER_USERNAME}</username>
                                    <password>${env.DOCKER_PASSWORD}</password>
                                </auth>
                            </to>
                            <container>
                                <ports>
                                    <port>7379</port>
                                </ports>
                                <jvmFlags>
                                    <jvmFlag>-Dspring.profiles.active=kubernetes</jvmFlag>
                                </jvmFlags>
                            </container>
                        </configuration>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>build</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>